let bdInitialAssignments  = [{"id":1,"nom":"Projet","dateDeRendu":"2021-02-14","rendu":true,"note":16,"remarque":"Très bon devoir, bravo","matiere":2,"etudiant":2},
{"id":2,"nom":"Devoir maison","dateDeRendu":"2021-11-05","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":4},
{"id":3,"nom":"TD noté","dateDeRendu":"2021-08-13","rendu":true,"note":13,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":1},
{"id":4,"nom":"Projet","dateDeRendu":"2021-03-23","rendu":true,"note":15,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":6},
{"id":5,"nom":"Devoir maison","dateDeRendu":"2021-06-29","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":3},
{"id":6,"nom":"Contrôle","dateDeRendu":"2022-01-06","rendu":true,"note":15,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":1},
{"id":7,"nom":"Devoir maison","dateDeRendu":"2021-06-17","rendu":true,"note":6,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":2,"etudiant":2},
{"id":8,"nom":"Contrôle","dateDeRendu":"2021-05-08","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":4},
{"id":9,"nom":"TD noté","dateDeRendu":"2021-04-28","rendu":true,"note":2,"remarque":"Revoir le chapitre en entier","matiere":3,"etudiant":4},
{"id":10,"nom":"Devoir maison","dateDeRendu":"2021-04-04","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":6},
{"id":11,"nom":"Oral","dateDeRendu":"2021-04-19","rendu":true,"note":14,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":4},
{"id":12,"nom":"Projet","dateDeRendu":"2021-04-09","rendu":true,"note":8,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":1,"etudiant":5},
{"id":13,"nom":"Projet","dateDeRendu":"2021-08-12","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":7},
{"id":14,"nom":"Devoir maison","dateDeRendu":"2021-06-06","rendu":true,"note":20,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":6},
{"id":15,"nom":"Oral","dateDeRendu":"2021-04-12","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":5},
{"id":16,"nom":"Contrôle","dateDeRendu":"2021-11-08","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":1,"etudiant":5},
{"id":17,"nom":"Contrôle","dateDeRendu":"2021-02-24","rendu":true,"note":11,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":4},
{"id":18,"nom":"Oral","dateDeRendu":"2021-05-07","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":2},
{"id":19,"nom":"Projet","dateDeRendu":"2021-07-21","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":2},
{"id":20,"nom":"Devoir maison","dateDeRendu":"2021-06-30","rendu":true,"note":14,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":1},
{"id":21,"nom":"Projet","dateDeRendu":"2021-05-30","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":5},
{"id":22,"nom":"Contrôle","dateDeRendu":"2021-09-21","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":2},
{"id":23,"nom":"TD noté","dateDeRendu":"2021-11-22","rendu":true,"note":4,"remarque":"Revoir le chapitre en entier","matiere":4,"etudiant":7},
{"id":24,"nom":"Oral","dateDeRendu":"2021-05-02","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":2},
{"id":25,"nom":"Oral","dateDeRendu":"2021-03-27","rendu":true,"note":16,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":1},
{"id":26,"nom":"TD noté","dateDeRendu":"2021-09-03","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":2},
{"id":27,"nom":"Oral","dateDeRendu":"2021-11-16","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":1},
{"id":28,"nom":"Contrôle","dateDeRendu":"2021-08-28","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":2},
{"id":29,"nom":"TD noté","dateDeRendu":"2021-06-19","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":2},
{"id":30,"nom":"TD noté","dateDeRendu":"2021-06-03","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":6},
{"id":31,"nom":"Oral","dateDeRendu":"2021-08-08","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":6},
{"id":32,"nom":"Oral","dateDeRendu":"2021-10-12","rendu":true,"note":19,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":1},
{"id":33,"nom":"Oral","dateDeRendu":"2021-06-05","rendu":true,"note":6,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":3,"etudiant":2},
{"id":34,"nom":"Projet","dateDeRendu":"2021-07-16","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":3},
{"id":35,"nom":"Projet","dateDeRendu":"2021-11-03","rendu":true,"note":16,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":1},
{"id":36,"nom":"Projet","dateDeRendu":"2021-08-13","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":4},
{"id":37,"nom":"Projet","dateDeRendu":"2021-05-27","rendu":true,"note":3,"remarque":"Revoir le chapitre en entier","matiere":3,"etudiant":7},
{"id":38,"nom":"Contrôle","dateDeRendu":"2021-03-31","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":4},
{"id":39,"nom":"Oral","dateDeRendu":"2021-07-07","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":1},
{"id":40,"nom":"TD noté","dateDeRendu":"2021-04-05","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":2},
{"id":41,"nom":"Projet","dateDeRendu":"2021-06-19","rendu":true,"note":17,"remarque":"Très bon devoir, bravo","matiere":2,"etudiant":2},
{"id":42,"nom":"Projet","dateDeRendu":"2021-06-17","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":7},
{"id":43,"nom":"Oral","dateDeRendu":"2021-03-21","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":2},
{"id":44,"nom":"Projet","dateDeRendu":"2021-12-12","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":4},
{"id":45,"nom":"Devoir maison","dateDeRendu":"2021-12-02","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":7},
{"id":46,"nom":"Projet","dateDeRendu":"2022-01-01","rendu":true,"note":6,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":2,"etudiant":5},
{"id":47,"nom":"TD noté","dateDeRendu":"2021-06-09","rendu":true,"note":4,"remarque":"Revoir le chapitre en entier","matiere":3,"etudiant":6},
{"id":48,"nom":"Oral","dateDeRendu":"2022-01-21","rendu":true,"note":17,"remarque":"Très bon devoir, bravo","matiere":2,"etudiant":7},
{"id":49,"nom":"Contrôle","dateDeRendu":"2021-05-17","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":1},
{"id":50,"nom":"Contrôle","dateDeRendu":"2021-07-15","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":3},
{"id":51,"nom":"Contrôle","dateDeRendu":"2021-07-05","rendu":true,"note":4,"remarque":"Revoir le chapitre en entier","matiere":1,"etudiant":1},
{"id":52,"nom":"Devoir maison","dateDeRendu":"2021-02-15","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":4},
{"id":53,"nom":"Devoir maison","dateDeRendu":"2021-02-27","rendu":true,"note":13,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":4},
{"id":54,"nom":"Devoir maison","dateDeRendu":"2021-06-05","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":6},
{"id":55,"nom":"Projet","dateDeRendu":"2021-01-29","rendu":true,"note":19,"remarque":"Très bon devoir, bravo","matiere":2,"etudiant":5},
{"id":56,"nom":"Projet","dateDeRendu":"2021-12-02","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":7},
{"id":57,"nom":"TD noté","dateDeRendu":"2021-05-13","rendu":true,"note":0,"remarque":"Revoir le chapitre en entier","matiere":1,"etudiant":4},
{"id":58,"nom":"Oral","dateDeRendu":"2021-10-07","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":6},
{"id":59,"nom":"Projet","dateDeRendu":"2021-05-29","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":5},
{"id":60,"nom":"TD noté","dateDeRendu":"2021-08-23","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":5},
{"id":61,"nom":"Oral","dateDeRendu":"2021-10-07","rendu":true,"note":11,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":2,"etudiant":3},
{"id":62,"nom":"Devoir maison","dateDeRendu":"2022-01-25","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":2},
{"id":63,"nom":"TD noté","dateDeRendu":"2021-03-03","rendu":true,"note":9,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":7},
{"id":64,"nom":"Contrôle","dateDeRendu":"2021-11-14","rendu":true,"note":0,"remarque":"Revoir le chapitre en entier","matiere":4,"etudiant":4},
{"id":65,"nom":"Projet","dateDeRendu":"2021-03-26","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":7},
{"id":66,"nom":"Devoir maison","dateDeRendu":"2021-09-30","rendu":true,"note":14,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":4},
{"id":67,"nom":"Devoir maison","dateDeRendu":"2021-07-05","rendu":true,"note":16,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":4},
{"id":68,"nom":"Contrôle","dateDeRendu":"2021-03-07","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":7},
{"id":69,"nom":"Devoir maison","dateDeRendu":"2021-11-13","rendu":true,"note":2,"remarque":"Revoir le chapitre en entier","matiere":3,"etudiant":7},
{"id":70,"nom":"Projet","dateDeRendu":"2021-08-24","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":7},
{"id":71,"nom":"TD noté","dateDeRendu":"2021-08-31","rendu":true,"note":7,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":1,"etudiant":4},
{"id":72,"nom":"Devoir maison","dateDeRendu":"2021-03-12","rendu":true,"note":7,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":2},
{"id":73,"nom":"Oral","dateDeRendu":"2022-01-15","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":3},
{"id":74,"nom":"Devoir maison","dateDeRendu":"2021-02-23","rendu":true,"note":7,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":3,"etudiant":4},
{"id":75,"nom":"Oral","dateDeRendu":"2021-09-04","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":2},
{"id":76,"nom":"Devoir maison","dateDeRendu":"2021-07-23","rendu":true,"note":11,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":1,"etudiant":5},
{"id":77,"nom":"Oral","dateDeRendu":"2021-12-05","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":6},
{"id":78,"nom":"Oral","dateDeRendu":"2021-08-24","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":3},
{"id":79,"nom":"Devoir maison","dateDeRendu":"2021-03-11","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":3},
{"id":80,"nom":"Devoir maison","dateDeRendu":"2021-06-23","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":5},
{"id":81,"nom":"TD noté","dateDeRendu":"2021-12-30","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":4},
{"id":82,"nom":"Oral","dateDeRendu":"2021-04-04","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":7},
{"id":83,"nom":"Contrôle","dateDeRendu":"2021-11-22","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":6},
{"id":84,"nom":"Contrôle","dateDeRendu":"2021-02-27","rendu":true,"note":11,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":3},
{"id":85,"nom":"Oral","dateDeRendu":"2021-12-24","rendu":true,"note":19,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":3},
{"id":86,"nom":"Projet","dateDeRendu":"2021-08-05","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":3},
{"id":87,"nom":"Contrôle","dateDeRendu":"2021-04-21","rendu":true,"note":4,"remarque":"Revoir le chapitre en entier","matiere":4,"etudiant":5},
{"id":88,"nom":"Projet","dateDeRendu":"2021-05-07","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":6},
{"id":89,"nom":"Oral","dateDeRendu":"2021-08-26","rendu":true,"note":13,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":1,"etudiant":3},
{"id":90,"nom":"Devoir maison","dateDeRendu":"2021-04-14","rendu":true,"note":20,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":5},
{"id":91,"nom":"Devoir maison","dateDeRendu":"2021-10-02","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":7},
{"id":92,"nom":"Devoir maison","dateDeRendu":"2021-10-01","rendu":true,"note":9,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":2,"etudiant":4},
{"id":93,"nom":"Contrôle","dateDeRendu":"2021-09-06","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":7},
{"id":94,"nom":"Projet","dateDeRendu":"2021-07-23","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":3},
{"id":95,"nom":"Devoir maison","dateDeRendu":"2021-09-02","rendu":true,"note":20,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":7},
{"id":96,"nom":"Projet","dateDeRendu":"2021-04-06","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":3},
{"id":97,"nom":"Oral","dateDeRendu":"2021-07-07","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":7},
{"id":98,"nom":"Devoir maison","dateDeRendu":"2021-02-14","rendu":true,"note":15,"remarque":"Très bon devoir, bravo","matiere":2,"etudiant":3},
{"id":99,"nom":"Devoir maison","dateDeRendu":"2021-08-31","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":4},
{"id":100,"nom":"Contrôle","dateDeRendu":"2021-06-05","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":2},
{"id":101,"nom":"Oral","dateDeRendu":"2021-07-04","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":5},
{"id":102,"nom":"Devoir maison","dateDeRendu":"2021-09-03","rendu":true,"note":13,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":1,"etudiant":3},
{"id":103,"nom":"TD noté","dateDeRendu":"2021-09-05","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":4},
{"id":104,"nom":"Projet","dateDeRendu":"2021-08-08","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":1},
{"id":105,"nom":"TD noté","dateDeRendu":"2021-07-18","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":5},
{"id":106,"nom":"Contrôle","dateDeRendu":"2021-06-03","rendu":true,"note":14,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":1,"etudiant":4},
{"id":107,"nom":"Projet","dateDeRendu":"2021-06-05","rendu":true,"note":13,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":2,"etudiant":1},
{"id":108,"nom":"Devoir maison","dateDeRendu":"2021-05-06","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":4},
{"id":109,"nom":"Contrôle","dateDeRendu":"2021-03-24","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":5},
{"id":110,"nom":"Devoir maison","dateDeRendu":"2021-02-17","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":5},
{"id":111,"nom":"Projet","dateDeRendu":"2021-12-26","rendu":true,"note":1,"remarque":"Revoir le chapitre en entier","matiere":3,"etudiant":6},
{"id":112,"nom":"TD noté","dateDeRendu":"2021-09-10","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":4},
{"id":113,"nom":"Projet","dateDeRendu":"2021-08-24","rendu":true,"note":1,"remarque":"Revoir le chapitre en entier","matiere":3,"etudiant":2},
{"id":114,"nom":"TD noté","dateDeRendu":"2021-12-25","rendu":true,"note":3,"remarque":"Revoir le chapitre en entier","matiere":2,"etudiant":2},
{"id":115,"nom":"Devoir maison","dateDeRendu":"2021-10-14","rendu":true,"note":20,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":1},
{"id":116,"nom":"Oral","dateDeRendu":"2021-08-05","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":3},
{"id":117,"nom":"Projet","dateDeRendu":"2021-07-12","rendu":true,"note":20,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":7},
{"id":118,"nom":"Devoir maison","dateDeRendu":"2021-05-22","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":1},
{"id":119,"nom":"TD noté","dateDeRendu":"2021-08-19","rendu":true,"note":8,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":2,"etudiant":6},
{"id":120,"nom":"Oral","dateDeRendu":"2021-10-29","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":4},
{"id":121,"nom":"Devoir maison","dateDeRendu":"2021-12-08","rendu":true,"note":0,"remarque":"Revoir le chapitre en entier","matiere":2,"etudiant":4},
{"id":122,"nom":"Projet","dateDeRendu":"2021-08-11","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":6},
{"id":123,"nom":"Projet","dateDeRendu":"2021-08-29","rendu":true,"note":20,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":6},
{"id":124,"nom":"Contrôle","dateDeRendu":"2021-04-17","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":1},
{"id":125,"nom":"Devoir maison","dateDeRendu":"2021-12-04","rendu":true,"note":1,"remarque":"Revoir le chapitre en entier","matiere":1,"etudiant":7},
{"id":126,"nom":"TD noté","dateDeRendu":"2021-05-12","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":5},
{"id":127,"nom":"Devoir maison","dateDeRendu":"2021-08-13","rendu":true,"note":19,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":1},
{"id":128,"nom":"Contrôle","dateDeRendu":"2021-07-16","rendu":true,"note":15,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":7},
{"id":129,"nom":"Projet","dateDeRendu":"2021-05-27","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":3},
{"id":130,"nom":"Devoir maison","dateDeRendu":"2021-06-11","rendu":true,"note":2,"remarque":"Revoir le chapitre en entier","matiere":4,"etudiant":2},
{"id":131,"nom":"Devoir maison","dateDeRendu":"2021-05-13","rendu":true,"note":15,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":7},
{"id":132,"nom":"Projet","dateDeRendu":"2021-06-26","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":4},
{"id":133,"nom":"TD noté","dateDeRendu":"2021-03-07","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":3},
{"id":134,"nom":"TD noté","dateDeRendu":"2021-03-20","rendu":true,"note":9,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":1,"etudiant":7},
{"id":135,"nom":"Contrôle","dateDeRendu":"2021-07-24","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":5},
{"id":136,"nom":"TD noté","dateDeRendu":"2021-02-26","rendu":true,"note":20,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":3},
{"id":137,"nom":"Devoir maison","dateDeRendu":"2021-05-12","rendu":true,"note":17,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":3},
{"id":138,"nom":"Oral","dateDeRendu":"2021-03-27","rendu":true,"note":20,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":5},
{"id":139,"nom":"Projet","dateDeRendu":"2021-08-13","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":3},
{"id":140,"nom":"Oral","dateDeRendu":"2021-04-07","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":2},
{"id":141,"nom":"Contrôle","dateDeRendu":"2021-03-16","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":1},
{"id":142,"nom":"TD noté","dateDeRendu":"2021-09-10","rendu":true,"note":5,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":1,"etudiant":2},
{"id":143,"nom":"Devoir maison","dateDeRendu":"2021-08-14","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":7},
{"id":144,"nom":"Projet","dateDeRendu":"2021-06-02","rendu":true,"note":19,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":4},
{"id":145,"nom":"Contrôle","dateDeRendu":"2021-02-22","rendu":true,"note":9,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":1,"etudiant":2},
{"id":146,"nom":"Oral","dateDeRendu":"2021-12-18","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":7},
{"id":147,"nom":"TD noté","dateDeRendu":"2021-12-20","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":5},
{"id":148,"nom":"Devoir maison","dateDeRendu":"2021-09-02","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":4},
{"id":149,"nom":"Projet","dateDeRendu":"2021-03-18","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":2},
{"id":150,"nom":"TD noté","dateDeRendu":"2021-04-01","rendu":true,"note":16,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":7},
{"id":151,"nom":"Projet","dateDeRendu":"2021-05-24","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":1},
{"id":152,"nom":"Contrôle","dateDeRendu":"2021-06-19","rendu":true,"note":12,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":1},
{"id":153,"nom":"Projet","dateDeRendu":"2021-09-23","rendu":true,"note":15,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":5},
{"id":154,"nom":"TD noté","dateDeRendu":"2021-05-29","rendu":true,"note":14,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":5},
{"id":155,"nom":"Contrôle","dateDeRendu":"2021-09-07","rendu":true,"note":3,"remarque":"Revoir le chapitre en entier","matiere":3,"etudiant":3},
{"id":156,"nom":"Projet","dateDeRendu":"2021-01-26","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":5},
{"id":157,"nom":"Contrôle","dateDeRendu":"2021-02-21","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":6},
{"id":158,"nom":"Devoir maison","dateDeRendu":"2021-06-05","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":4},
{"id":159,"nom":"Oral","dateDeRendu":"2021-10-19","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":5},
{"id":160,"nom":"Devoir maison","dateDeRendu":"2021-02-28","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":3},
{"id":161,"nom":"TD noté","dateDeRendu":"2021-03-19","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":5},
{"id":162,"nom":"Contrôle","dateDeRendu":"2021-04-23","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":2},
{"id":163,"nom":"Devoir maison","dateDeRendu":"2021-08-09","rendu":true,"note":16,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":6},
{"id":164,"nom":"Projet","dateDeRendu":"2022-01-19","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":7},
{"id":165,"nom":"Devoir maison","dateDeRendu":"2021-03-06","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":1},
{"id":166,"nom":"Devoir maison","dateDeRendu":"2021-02-27","rendu":true,"note":8,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":3,"etudiant":5},
{"id":167,"nom":"Devoir maison","dateDeRendu":"2021-06-25","rendu":true,"note":19,"remarque":"Très bon devoir, bravo","matiere":2,"etudiant":7},
{"id":168,"nom":"Oral","dateDeRendu":"2022-01-15","rendu":true,"note":11,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":4},
{"id":169,"nom":"Oral","dateDeRendu":"2021-06-01","rendu":true,"note":20,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":5},
{"id":170,"nom":"TD noté","dateDeRendu":"2021-05-08","rendu":true,"note":14,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":1,"etudiant":1},
{"id":171,"nom":"Contrôle","dateDeRendu":"2021-08-09","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":6},
{"id":172,"nom":"Projet","dateDeRendu":"2021-10-10","rendu":true,"note":17,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":4},
{"id":173,"nom":"Projet","dateDeRendu":"2021-11-15","rendu":true,"note":0,"remarque":"Revoir le chapitre en entier","matiere":1,"etudiant":1},
{"id":174,"nom":"Oral","dateDeRendu":"2021-02-10","rendu":true,"note":6,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":3,"etudiant":7},
{"id":175,"nom":"Devoir maison","dateDeRendu":"2021-04-07","rendu":true,"note":2,"remarque":"Revoir le chapitre en entier","matiere":3,"etudiant":2},
{"id":176,"nom":"Projet","dateDeRendu":"2021-10-03","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":4},
{"id":177,"nom":"Oral","dateDeRendu":"2021-10-30","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":6},
{"id":178,"nom":"Projet","dateDeRendu":"2021-09-17","rendu":true,"note":5,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":1,"etudiant":6},
{"id":179,"nom":"Projet","dateDeRendu":"2021-11-16","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":2,"etudiant":3},
{"id":180,"nom":"Projet","dateDeRendu":"2021-04-08","rendu":true,"note":6,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":7},
{"id":181,"nom":"TD noté","dateDeRendu":"2021-12-28","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":7},
{"id":182,"nom":"Projet","dateDeRendu":"2021-06-11","rendu":true,"note":18,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":5},
{"id":183,"nom":"Projet","dateDeRendu":"2021-05-21","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":6},
{"id":184,"nom":"Oral","dateDeRendu":"2021-12-20","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":5},
{"id":185,"nom":"Oral","dateDeRendu":"2021-11-23","rendu":true,"note":7,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":3,"etudiant":1},
{"id":186,"nom":"TD noté","dateDeRendu":"2021-09-15","rendu":true,"note":16,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":6},
{"id":187,"nom":"Devoir maison","dateDeRendu":"2021-03-23","rendu":true,"note":0,"remarque":"Revoir le chapitre en entier","matiere":2,"etudiant":2},
{"id":188,"nom":"Devoir maison","dateDeRendu":"2021-05-26","rendu":true,"note":5,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":2,"etudiant":2},
{"id":189,"nom":"Contrôle","dateDeRendu":"2021-02-06","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":2},
{"id":190,"nom":"Oral","dateDeRendu":"2021-12-30","rendu":true,"note":12,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":2},
{"id":191,"nom":"Devoir maison","dateDeRendu":"2021-02-10","rendu":true,"note":8,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":3,"etudiant":6},
{"id":192,"nom":"Oral","dateDeRendu":"2021-12-19","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":7},
{"id":193,"nom":"Contrôle","dateDeRendu":"2021-10-05","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":5},
{"id":194,"nom":"Oral","dateDeRendu":"2021-09-27","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":7},
{"id":195,"nom":"Projet","dateDeRendu":"2021-11-05","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":7},
{"id":196,"nom":"TD noté","dateDeRendu":"2021-07-21","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":6},
{"id":197,"nom":"Contrôle","dateDeRendu":"2021-11-23","rendu":true,"note":18,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":1},
{"id":198,"nom":"Projet","dateDeRendu":"2021-12-16","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":1},
{"id":199,"nom":"Devoir maison","dateDeRendu":"2021-07-13","rendu":true,"note":4,"remarque":"Revoir le chapitre en entier","matiere":2,"etudiant":7},
{"id":200,"nom":"Devoir maison","dateDeRendu":"2022-01-15","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":6},
{"id":201,"nom":"Contrôle","dateDeRendu":"2021-08-03","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":4},
{"id":202,"nom":"Contrôle","dateDeRendu":"2022-01-15","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":6},
{"id":203,"nom":"TD noté","dateDeRendu":"2021-08-09","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":3},
{"id":204,"nom":"Contrôle","dateDeRendu":"2022-01-19","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":1},
{"id":205,"nom":"Contrôle","dateDeRendu":"2021-02-17","rendu":true,"note":5,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":2,"etudiant":7},
{"id":206,"nom":"TD noté","dateDeRendu":"2021-04-27","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":5},
{"id":207,"nom":"Contrôle","dateDeRendu":"2021-05-11","rendu":true,"note":0,"remarque":"Revoir le chapitre en entier","matiere":2,"etudiant":2},
{"id":208,"nom":"Oral","dateDeRendu":"2021-07-24","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":7},
{"id":209,"nom":"Contrôle","dateDeRendu":"2021-12-20","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":7},
{"id":210,"nom":"Devoir maison","dateDeRendu":"2021-11-25","rendu":true,"note":7,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":7},
{"id":211,"nom":"Contrôle","dateDeRendu":"2021-12-26","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":5},
{"id":212,"nom":"TD noté","dateDeRendu":"2021-02-03","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":1},
{"id":213,"nom":"Projet","dateDeRendu":"2022-01-15","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":7},
{"id":214,"nom":"Devoir maison","dateDeRendu":"2021-09-19","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":2},
{"id":215,"nom":"TD noté","dateDeRendu":"2021-06-18","rendu":true,"note":5,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":2,"etudiant":3},
{"id":216,"nom":"Devoir maison","dateDeRendu":"2021-05-23","rendu":true,"note":3,"remarque":"Revoir le chapitre en entier","matiere":4,"etudiant":4},
{"id":217,"nom":"Devoir maison","dateDeRendu":"2021-06-15","rendu":true,"note":7,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":1,"etudiant":1},
{"id":218,"nom":"Devoir maison","dateDeRendu":"2021-11-01","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":5},
{"id":219,"nom":"Contrôle","dateDeRendu":"2021-05-24","rendu":true,"note":2,"remarque":"Revoir le chapitre en entier","matiere":2,"etudiant":4},
{"id":220,"nom":"Oral","dateDeRendu":"2021-11-22","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":7},
{"id":221,"nom":"Projet","dateDeRendu":"2021-12-03","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":3},
{"id":222,"nom":"Contrôle","dateDeRendu":"2021-09-16","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":1},
{"id":223,"nom":"Contrôle","dateDeRendu":"2021-03-19","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":2},
{"id":224,"nom":"Projet","dateDeRendu":"2021-04-12","rendu":true,"note":16,"remarque":"Très bon devoir, bravo","matiere":2,"etudiant":1},
{"id":225,"nom":"Contrôle","dateDeRendu":"2021-01-26","rendu":true,"note":6,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":2,"etudiant":2},
{"id":226,"nom":"Oral","dateDeRendu":"2021-05-30","rendu":true,"note":12,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":6},
{"id":227,"nom":"Contrôle","dateDeRendu":"2021-10-19","rendu":true,"note":13,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":2,"etudiant":6},
{"id":228,"nom":"Projet","dateDeRendu":"2021-10-07","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":7},
{"id":229,"nom":"Projet","dateDeRendu":"2021-02-14","rendu":true,"note":18,"remarque":"Très bon devoir, bravo","matiere":2,"etudiant":1},
{"id":230,"nom":"Devoir maison","dateDeRendu":"2021-09-04","rendu":true,"note":4,"remarque":"Revoir le chapitre en entier","matiere":2,"etudiant":3},
{"id":231,"nom":"TD noté","dateDeRendu":"2022-01-21","rendu":true,"note":9,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":3},
{"id":232,"nom":"Contrôle","dateDeRendu":"2021-10-10","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":7},
{"id":233,"nom":"Projet","dateDeRendu":"2021-11-19","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":3},
{"id":234,"nom":"Devoir maison","dateDeRendu":"2021-07-10","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":4},
{"id":235,"nom":"Contrôle","dateDeRendu":"2021-03-28","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":2},
{"id":236,"nom":"TD noté","dateDeRendu":"2021-07-12","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":2},
{"id":237,"nom":"Oral","dateDeRendu":"2021-05-27","rendu":true,"note":4,"remarque":"Revoir le chapitre en entier","matiere":4,"etudiant":4},
{"id":238,"nom":"Contrôle","dateDeRendu":"2021-06-03","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":2},
{"id":239,"nom":"Contrôle","dateDeRendu":"2021-07-13","rendu":true,"note":16,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":1},
{"id":240,"nom":"Devoir maison","dateDeRendu":"2021-12-21","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":2},
{"id":241,"nom":"Projet","dateDeRendu":"2021-11-10","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":7},
{"id":242,"nom":"TD noté","dateDeRendu":"2021-03-30","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":1},
{"id":243,"nom":"Oral","dateDeRendu":"2021-12-18","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":7},
{"id":244,"nom":"Oral","dateDeRendu":"2021-08-29","rendu":true,"note":4,"remarque":"Revoir le chapitre en entier","matiere":2,"etudiant":4},
{"id":245,"nom":"Devoir maison","dateDeRendu":"2021-03-20","rendu":true,"note":6,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":3,"etudiant":7},
{"id":246,"nom":"Projet","dateDeRendu":"2021-02-24","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":5},
{"id":247,"nom":"Oral","dateDeRendu":"2021-12-25","rendu":true,"note":9,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":1},
{"id":248,"nom":"Devoir maison","dateDeRendu":"2021-04-18","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":1},
{"id":249,"nom":"Devoir maison","dateDeRendu":"2021-09-24","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":5},
{"id":250,"nom":"Oral","dateDeRendu":"2022-01-10","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":4},
{"id":251,"nom":"Devoir maison","dateDeRendu":"2021-01-31","rendu":true,"note":14,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":2,"etudiant":4},
{"id":252,"nom":"Devoir maison","dateDeRendu":"2021-08-05","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":3},
{"id":253,"nom":"Oral","dateDeRendu":"2021-08-26","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":6},
{"id":254,"nom":"TD noté","dateDeRendu":"2021-10-05","rendu":true,"note":0,"remarque":"Revoir le chapitre en entier","matiere":2,"etudiant":1},
{"id":255,"nom":"Oral","dateDeRendu":"2021-06-16","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":2},
{"id":256,"nom":"TD noté","dateDeRendu":"2021-04-19","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":1},
{"id":257,"nom":"TD noté","dateDeRendu":"2021-04-28","rendu":true,"note":20,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":2},
{"id":258,"nom":"Projet","dateDeRendu":"2021-03-18","rendu":true,"note":7,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":2,"etudiant":5},
{"id":259,"nom":"Contrôle","dateDeRendu":"2021-12-24","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":7},
{"id":260,"nom":"Oral","dateDeRendu":"2021-11-23","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":5},
{"id":261,"nom":"TD noté","dateDeRendu":"2021-09-14","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":6},
{"id":262,"nom":"TD noté","dateDeRendu":"2021-04-14","rendu":true,"note":13,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":1},
{"id":263,"nom":"Oral","dateDeRendu":"2021-08-22","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":5},
{"id":264,"nom":"Oral","dateDeRendu":"2021-07-20","rendu":true,"note":16,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":2},
{"id":265,"nom":"Contrôle","dateDeRendu":"2021-09-12","rendu":true,"note":8,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":4},
{"id":266,"nom":"Projet","dateDeRendu":"2021-08-03","rendu":true,"note":0,"remarque":"Revoir le chapitre en entier","matiere":4,"etudiant":7},
{"id":267,"nom":"Contrôle","dateDeRendu":"2021-03-25","rendu":true,"note":7,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":6},
{"id":268,"nom":"Contrôle","dateDeRendu":"2021-09-23","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":6},
{"id":269,"nom":"Contrôle","dateDeRendu":"2021-10-30","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":3},
{"id":270,"nom":"Projet","dateDeRendu":"2021-04-29","rendu":true,"note":1,"remarque":"Revoir le chapitre en entier","matiere":4,"etudiant":3},
{"id":271,"nom":"Devoir maison","dateDeRendu":"2022-01-11","rendu":true,"note":12,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":5},
{"id":272,"nom":"Oral","dateDeRendu":"2021-03-09","rendu":true,"note":15,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":7},
{"id":273,"nom":"Contrôle","dateDeRendu":"2021-11-07","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":1},
{"id":274,"nom":"Oral","dateDeRendu":"2021-05-16","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":5},
{"id":275,"nom":"Oral","dateDeRendu":"2022-01-07","rendu":true,"note":15,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":2},
{"id":276,"nom":"Contrôle","dateDeRendu":"2021-08-06","rendu":true,"note":12,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":7},
{"id":277,"nom":"Oral","dateDeRendu":"2021-02-25","rendu":true,"note":3,"remarque":"Revoir le chapitre en entier","matiere":4,"etudiant":2},
{"id":278,"nom":"Projet","dateDeRendu":"2021-06-18","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":6},
{"id":279,"nom":"TD noté","dateDeRendu":"2021-03-21","rendu":true,"note":2,"remarque":"Revoir le chapitre en entier","matiere":4,"etudiant":4},
{"id":280,"nom":"Devoir maison","dateDeRendu":"2021-03-25","rendu":true,"note":6,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":3},
{"id":281,"nom":"Projet","dateDeRendu":"2021-05-05","rendu":true,"note":17,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":4},
{"id":282,"nom":"Oral","dateDeRendu":"2021-02-19","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":2},
{"id":283,"nom":"Contrôle","dateDeRendu":"2021-06-04","rendu":true,"note":19,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":6},
{"id":284,"nom":"Contrôle","dateDeRendu":"2021-05-06","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":1,"etudiant":1},
{"id":285,"nom":"TD noté","dateDeRendu":"2021-11-27","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":4},
{"id":286,"nom":"TD noté","dateDeRendu":"2021-11-06","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":4},
{"id":287,"nom":"Oral","dateDeRendu":"2021-06-14","rendu":true,"note":7,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":3,"etudiant":7},
{"id":288,"nom":"Oral","dateDeRendu":"2022-01-07","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":4},
{"id":289,"nom":"Oral","dateDeRendu":"2021-06-18","rendu":true,"note":15,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":5},
{"id":290,"nom":"TD noté","dateDeRendu":"2021-05-03","rendu":true,"note":3,"remarque":"Revoir le chapitre en entier","matiere":2,"etudiant":1},
{"id":291,"nom":"Devoir maison","dateDeRendu":"2021-04-27","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":4},
{"id":292,"nom":"Projet","dateDeRendu":"2021-05-15","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":2,"etudiant":3},
{"id":293,"nom":"Oral","dateDeRendu":"2021-11-06","rendu":true,"note":6,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":3,"etudiant":2},
{"id":294,"nom":"Projet","dateDeRendu":"2021-09-20","rendu":true,"note":13,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":6},
{"id":295,"nom":"Devoir maison","dateDeRendu":"2021-06-08","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":1},
{"id":296,"nom":"Projet","dateDeRendu":"2021-04-07","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":7},
{"id":297,"nom":"Oral","dateDeRendu":"2021-06-19","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":4},
{"id":298,"nom":"Oral","dateDeRendu":"2021-08-08","rendu":true,"note":8,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":4},
{"id":299,"nom":"Projet","dateDeRendu":"2021-09-24","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":1},
{"id":300,"nom":"Oral","dateDeRendu":"2021-07-20","rendu":true,"note":18,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":5},
{"id":301,"nom":"Devoir maison","dateDeRendu":"2021-05-25","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":4},
{"id":302,"nom":"Devoir maison","dateDeRendu":"2021-08-13","rendu":true,"note":8,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":6},
{"id":303,"nom":"Oral","dateDeRendu":"2021-10-18","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":3},
{"id":304,"nom":"Projet","dateDeRendu":"2021-10-04","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":3},
{"id":305,"nom":"Oral","dateDeRendu":"2021-06-30","rendu":true,"note":14,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":1,"etudiant":7},
{"id":306,"nom":"Projet","dateDeRendu":"2021-10-08","rendu":true,"note":12,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":1,"etudiant":5},
{"id":307,"nom":"Devoir maison","dateDeRendu":"2021-04-19","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":1},
{"id":308,"nom":"Oral","dateDeRendu":"2021-11-29","rendu":true,"note":7,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":2,"etudiant":4},
{"id":309,"nom":"Projet","dateDeRendu":"2021-06-15","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":5},
{"id":310,"nom":"TD noté","dateDeRendu":"2021-09-15","rendu":true,"note":9,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":3,"etudiant":4},
{"id":311,"nom":"Devoir maison","dateDeRendu":"2021-03-18","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":6},
{"id":312,"nom":"Projet","dateDeRendu":"2021-10-27","rendu":true,"note":15,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":2},
{"id":313,"nom":"TD noté","dateDeRendu":"2021-08-24","rendu":true,"note":11,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":2},
{"id":314,"nom":"Contrôle","dateDeRendu":"2021-04-25","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":5},
{"id":315,"nom":"TD noté","dateDeRendu":"2021-06-16","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":2,"etudiant":7},
{"id":316,"nom":"Oral","dateDeRendu":"2021-09-02","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":2},
{"id":317,"nom":"Oral","dateDeRendu":"2021-07-05","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":6},
{"id":318,"nom":"Projet","dateDeRendu":"2021-02-07","rendu":true,"note":9,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":2,"etudiant":1},
{"id":319,"nom":"Contrôle","dateDeRendu":"2021-12-11","rendu":true,"note":6,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":7},
{"id":320,"nom":"TD noté","dateDeRendu":"2021-02-14","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":5},
{"id":321,"nom":"Devoir maison","dateDeRendu":"2021-02-12","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":6},
{"id":322,"nom":"Contrôle","dateDeRendu":"2021-07-19","rendu":true,"note":17,"remarque":"Très bon devoir, bravo","matiere":2,"etudiant":7},
{"id":323,"nom":"Contrôle","dateDeRendu":"2021-12-02","rendu":true,"note":19,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":5},
{"id":324,"nom":"TD noté","dateDeRendu":"2021-06-21","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":1,"etudiant":3},
{"id":325,"nom":"Contrôle","dateDeRendu":"2021-02-02","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":2,"etudiant":7},
{"id":326,"nom":"Contrôle","dateDeRendu":"2021-09-30","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":2},
{"id":327,"nom":"Projet","dateDeRendu":"2021-12-05","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":1},
{"id":328,"nom":"TD noté","dateDeRendu":"2021-10-22","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":4},
{"id":329,"nom":"TD noté","dateDeRendu":"2021-05-14","rendu":true,"note":0,"remarque":"Revoir le chapitre en entier","matiere":2,"etudiant":7},
{"id":330,"nom":"Contrôle","dateDeRendu":"2021-04-05","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":2},
{"id":331,"nom":"TD noté","dateDeRendu":"2021-12-08","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":2},
{"id":332,"nom":"TD noté","dateDeRendu":"2021-04-22","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":3},
{"id":333,"nom":"Contrôle","dateDeRendu":"2021-09-27","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":4},
{"id":334,"nom":"TD noté","dateDeRendu":"2021-05-07","rendu":true,"note":6,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":3,"etudiant":4},
{"id":335,"nom":"TD noté","dateDeRendu":"2021-02-02","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":2},
{"id":336,"nom":"Projet","dateDeRendu":"2021-09-04","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":2},
{"id":337,"nom":"Devoir maison","dateDeRendu":"2021-11-24","rendu":true,"note":18,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":3},
{"id":338,"nom":"Projet","dateDeRendu":"2021-04-29","rendu":true,"note":18,"remarque":"Très bon devoir, bravo","matiere":2,"etudiant":6},
{"id":339,"nom":"Projet","dateDeRendu":"2021-09-27","rendu":true,"note":19,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":7},
{"id":340,"nom":"TD noté","dateDeRendu":"2021-06-21","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":3},
{"id":341,"nom":"Oral","dateDeRendu":"2021-04-28","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":3},
{"id":342,"nom":"TD noté","dateDeRendu":"2021-02-19","rendu":true,"note":15,"remarque":"Très bon devoir, bravo","matiere":2,"etudiant":1},
{"id":343,"nom":"Devoir maison","dateDeRendu":"2021-09-21","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":1},
{"id":344,"nom":"Devoir maison","dateDeRendu":"2021-07-14","rendu":true,"note":18,"remarque":"Très bon devoir, bravo","matiere":2,"etudiant":2},
{"id":345,"nom":"Projet","dateDeRendu":"2021-05-16","rendu":true,"note":6,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":2,"etudiant":3},
{"id":346,"nom":"Devoir maison","dateDeRendu":"2021-03-02","rendu":true,"note":5,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":3,"etudiant":2},
{"id":347,"nom":"Devoir maison","dateDeRendu":"2021-10-15","rendu":true,"note":11,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":1},
{"id":348,"nom":"Contrôle","dateDeRendu":"2021-05-11","rendu":true,"note":6,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":1,"etudiant":3},
{"id":349,"nom":"Contrôle","dateDeRendu":"2021-08-15","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":7},
{"id":350,"nom":"TD noté","dateDeRendu":"2021-12-20","rendu":true,"note":5,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":1,"etudiant":4},
{"id":351,"nom":"TD noté","dateDeRendu":"2021-03-30","rendu":true,"note":13,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":1},
{"id":352,"nom":"Devoir maison","dateDeRendu":"2021-03-26","rendu":true,"note":20,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":3},
{"id":353,"nom":"Devoir maison","dateDeRendu":"2021-05-29","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":4},
{"id":354,"nom":"Oral","dateDeRendu":"2021-06-15","rendu":true,"note":9,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":2},
{"id":355,"nom":"TD noté","dateDeRendu":"2021-06-28","rendu":true,"note":15,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":6},
{"id":356,"nom":"Contrôle","dateDeRendu":"2021-07-04","rendu":true,"note":17,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":3},
{"id":357,"nom":"Contrôle","dateDeRendu":"2021-12-24","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":3},
{"id":358,"nom":"Oral","dateDeRendu":"2021-04-26","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":2},
{"id":359,"nom":"Projet","dateDeRendu":"2021-12-09","rendu":true,"note":4,"remarque":"Revoir le chapitre en entier","matiere":1,"etudiant":1},
{"id":360,"nom":"Projet","dateDeRendu":"2021-09-11","rendu":true,"note":8,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":2,"etudiant":7},
{"id":361,"nom":"Devoir maison","dateDeRendu":"2021-03-15","rendu":true,"note":15,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":3},
{"id":362,"nom":"Devoir maison","dateDeRendu":"2021-07-07","rendu":true,"note":13,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":6},
{"id":363,"nom":"TD noté","dateDeRendu":"2021-07-12","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":2},
{"id":364,"nom":"Devoir maison","dateDeRendu":"2021-06-24","rendu":true,"note":11,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":1,"etudiant":2},
{"id":365,"nom":"Oral","dateDeRendu":"2022-01-07","rendu":true,"note":19,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":5},
{"id":366,"nom":"Projet","dateDeRendu":"2021-08-28","rendu":true,"note":13,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":2,"etudiant":3},
{"id":367,"nom":"Devoir maison","dateDeRendu":"2021-09-14","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":7},
{"id":368,"nom":"TD noté","dateDeRendu":"2021-11-13","rendu":true,"note":5,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":1},
{"id":369,"nom":"Oral","dateDeRendu":"2021-08-10","rendu":true,"note":6,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":2,"etudiant":4},
{"id":370,"nom":"Devoir maison","dateDeRendu":"2021-06-28","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":2,"etudiant":1},
{"id":371,"nom":"Projet","dateDeRendu":"2021-06-14","rendu":true,"note":8,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":3},
{"id":372,"nom":"TD noté","dateDeRendu":"2021-02-15","rendu":true,"note":4,"remarque":"Revoir le chapitre en entier","matiere":3,"etudiant":7},
{"id":373,"nom":"TD noté","dateDeRendu":"2021-03-12","rendu":true,"note":12,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":7},
{"id":374,"nom":"Oral","dateDeRendu":"2021-01-28","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":1},
{"id":375,"nom":"Projet","dateDeRendu":"2021-06-14","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":6},
{"id":376,"nom":"Projet","dateDeRendu":"2021-03-19","rendu":true,"note":17,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":2},
{"id":377,"nom":"Contrôle","dateDeRendu":"2021-06-23","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":2},
{"id":378,"nom":"Oral","dateDeRendu":"2021-09-06","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":1},
{"id":379,"nom":"Projet","dateDeRendu":"2021-05-31","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":7},
{"id":380,"nom":"Contrôle","dateDeRendu":"2021-09-06","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":1},
{"id":381,"nom":"Contrôle","dateDeRendu":"2021-11-06","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":2},
{"id":382,"nom":"Devoir maison","dateDeRendu":"2021-06-12","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":1},
{"id":383,"nom":"Projet","dateDeRendu":"2021-11-09","rendu":true,"note":14,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":5},
{"id":384,"nom":"TD noté","dateDeRendu":"2021-03-28","rendu":true,"note":8,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":3,"etudiant":3},
{"id":385,"nom":"TD noté","dateDeRendu":"2021-02-11","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":2,"etudiant":3},
{"id":386,"nom":"Devoir maison","dateDeRendu":"2021-10-11","rendu":true,"note":12,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":1,"etudiant":6},
{"id":387,"nom":"Projet","dateDeRendu":"2021-01-29","rendu":true,"note":3,"remarque":"Revoir le chapitre en entier","matiere":4,"etudiant":2},
{"id":388,"nom":"TD noté","dateDeRendu":"2022-01-03","rendu":true,"note":13,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":7},
{"id":389,"nom":"Contrôle","dateDeRendu":"2021-09-04","rendu":true,"note":18,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":3},
{"id":390,"nom":"TD noté","dateDeRendu":"2021-05-26","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":3},
{"id":391,"nom":"Oral","dateDeRendu":"2021-12-12","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":4},
{"id":392,"nom":"Devoir maison","dateDeRendu":"2021-04-15","rendu":true,"note":19,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":6},
{"id":393,"nom":"Oral","dateDeRendu":"2021-11-03","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":1},
{"id":394,"nom":"Oral","dateDeRendu":"2021-09-28","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":1},
{"id":395,"nom":"Devoir maison","dateDeRendu":"2021-04-27","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":4},
{"id":396,"nom":"Oral","dateDeRendu":"2021-09-07","rendu":true,"note":8,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":5},
{"id":397,"nom":"Contrôle","dateDeRendu":"2021-07-21","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":1},
{"id":398,"nom":"Contrôle","dateDeRendu":"2021-11-27","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":3},
{"id":399,"nom":"Devoir maison","dateDeRendu":"2021-10-02","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":3},
{"id":400,"nom":"Projet","dateDeRendu":"2021-02-25","rendu":true,"note":1,"remarque":"Revoir le chapitre en entier","matiere":3,"etudiant":6},
{"id":401,"nom":"TD noté","dateDeRendu":"2021-05-24","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":6},
{"id":402,"nom":"TD noté","dateDeRendu":"2021-07-13","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":2},
{"id":403,"nom":"Contrôle","dateDeRendu":"2021-07-17","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":5},
{"id":404,"nom":"Projet","dateDeRendu":"2021-10-23","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":6},
{"id":405,"nom":"Contrôle","dateDeRendu":"2022-01-14","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":2},
{"id":406,"nom":"Devoir maison","dateDeRendu":"2021-03-17","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":5},
{"id":407,"nom":"TD noté","dateDeRendu":"2021-09-07","rendu":true,"note":6,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":2,"etudiant":2},
{"id":408,"nom":"TD noté","dateDeRendu":"2021-03-19","rendu":true,"note":0,"remarque":"Revoir le chapitre en entier","matiere":1,"etudiant":4},
{"id":409,"nom":"Contrôle","dateDeRendu":"2021-12-02","rendu":true,"note":18,"remarque":"Très bon devoir, bravo","matiere":2,"etudiant":1},
{"id":410,"nom":"Projet","dateDeRendu":"2021-08-28","rendu":true,"note":12,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":6},
{"id":411,"nom":"Oral","dateDeRendu":"2021-01-26","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":3},
{"id":412,"nom":"Projet","dateDeRendu":"2021-11-05","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":6},
{"id":413,"nom":"Oral","dateDeRendu":"2021-02-19","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":7},
{"id":414,"nom":"TD noté","dateDeRendu":"2021-09-05","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":4},
{"id":415,"nom":"Projet","dateDeRendu":"2021-06-23","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":4},
{"id":416,"nom":"Devoir maison","dateDeRendu":"2021-07-29","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":7},
{"id":417,"nom":"TD noté","dateDeRendu":"2021-03-08","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":3},
{"id":418,"nom":"Projet","dateDeRendu":"2021-09-10","rendu":true,"note":7,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":1,"etudiant":3},
{"id":419,"nom":"Oral","dateDeRendu":"2021-09-11","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":3},
{"id":420,"nom":"Projet","dateDeRendu":"2021-04-14","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":1},
{"id":421,"nom":"Contrôle","dateDeRendu":"2021-12-07","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":5},
{"id":422,"nom":"Oral","dateDeRendu":"2021-03-02","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":3},
{"id":423,"nom":"Contrôle","dateDeRendu":"2021-09-16","rendu":true,"note":11,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":1,"etudiant":3},
{"id":424,"nom":"Projet","dateDeRendu":"2021-04-22","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":7},
{"id":425,"nom":"Contrôle","dateDeRendu":"2021-09-14","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":6},
{"id":426,"nom":"Oral","dateDeRendu":"2022-01-08","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":7},
{"id":427,"nom":"Projet","dateDeRendu":"2021-07-02","rendu":true,"note":9,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":1,"etudiant":7},
{"id":428,"nom":"TD noté","dateDeRendu":"2021-04-19","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":1},
{"id":429,"nom":"TD noté","dateDeRendu":"2021-02-13","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":6},
{"id":430,"nom":"Projet","dateDeRendu":"2021-09-04","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":2},
{"id":431,"nom":"Contrôle","dateDeRendu":"2021-04-01","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":7},
{"id":432,"nom":"Contrôle","dateDeRendu":"2021-10-24","rendu":true,"note":16,"remarque":"Très bon devoir, bravo","matiere":2,"etudiant":1},
{"id":433,"nom":"Contrôle","dateDeRendu":"2021-11-03","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":2},
{"id":434,"nom":"Oral","dateDeRendu":"2021-08-09","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":2},
{"id":435,"nom":"Oral","dateDeRendu":"2022-01-19","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":4},
{"id":436,"nom":"TD noté","dateDeRendu":"2021-02-22","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":4},
{"id":437,"nom":"Contrôle","dateDeRendu":"2021-09-10","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":4},
{"id":438,"nom":"TD noté","dateDeRendu":"2021-08-11","rendu":true,"note":9,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":1,"etudiant":7},
{"id":439,"nom":"Devoir maison","dateDeRendu":"2021-02-10","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":1},
{"id":440,"nom":"TD noté","dateDeRendu":"2021-10-26","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":5},
{"id":441,"nom":"Devoir maison","dateDeRendu":"2021-11-24","rendu":true,"note":19,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":7},
{"id":442,"nom":"TD noté","dateDeRendu":"2021-04-10","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":7},
{"id":443,"nom":"TD noté","dateDeRendu":"2021-05-21","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":7},
{"id":444,"nom":"Projet","dateDeRendu":"2021-11-06","rendu":true,"note":2,"remarque":"Revoir le chapitre en entier","matiere":1,"etudiant":5},
{"id":445,"nom":"TD noté","dateDeRendu":"2021-03-02","rendu":true,"note":16,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":3},
{"id":446,"nom":"Projet","dateDeRendu":"2021-10-07","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":6},
{"id":447,"nom":"Devoir maison","dateDeRendu":"2022-01-06","rendu":true,"note":19,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":5},
{"id":448,"nom":"Oral","dateDeRendu":"2021-07-08","rendu":true,"note":16,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":4},
{"id":449,"nom":"Oral","dateDeRendu":"2021-05-17","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":3},
{"id":450,"nom":"Devoir maison","dateDeRendu":"2021-08-03","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":3},
{"id":451,"nom":"Devoir maison","dateDeRendu":"2021-11-22","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":6},
{"id":452,"nom":"TD noté","dateDeRendu":"2021-04-22","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":3},
{"id":453,"nom":"TD noté","dateDeRendu":"2021-09-25","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":7},
{"id":454,"nom":"TD noté","dateDeRendu":"2021-12-24","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":6},
{"id":455,"nom":"Oral","dateDeRendu":"2021-05-13","rendu":true,"note":1,"remarque":"Revoir le chapitre en entier","matiere":2,"etudiant":1},
{"id":456,"nom":"Projet","dateDeRendu":"2021-10-02","rendu":true,"note":17,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":2},
{"id":457,"nom":"Contrôle","dateDeRendu":"2021-09-22","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":6},
{"id":458,"nom":"Projet","dateDeRendu":"2022-01-18","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":4},
{"id":459,"nom":"Oral","dateDeRendu":"2022-01-19","rendu":true,"note":4,"remarque":"Revoir le chapitre en entier","matiere":3,"etudiant":1},
{"id":460,"nom":"Contrôle","dateDeRendu":"2021-01-28","rendu":true,"note":20,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":6},
{"id":461,"nom":"Contrôle","dateDeRendu":"2021-10-25","rendu":true,"note":16,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":4},
{"id":462,"nom":"Projet","dateDeRendu":"2021-12-09","rendu":true,"note":17,"remarque":"Très bon devoir, bravo","matiere":3,"etudiant":6},
{"id":463,"nom":"TD noté","dateDeRendu":"2021-09-14","rendu":true,"note":11,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":1},
{"id":464,"nom":"Projet","dateDeRendu":"2021-06-25","rendu":true,"note":14,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":2,"etudiant":2},
{"id":465,"nom":"Projet","dateDeRendu":"2021-06-13","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":7},
{"id":466,"nom":"Projet","dateDeRendu":"2021-02-12","rendu":true,"note":1,"remarque":"Revoir le chapitre en entier","matiere":3,"etudiant":7},
{"id":467,"nom":"TD noté","dateDeRendu":"2021-09-20","rendu":true,"note":0,"remarque":"Revoir le chapitre en entier","matiere":2,"etudiant":6},
{"id":468,"nom":"Oral","dateDeRendu":"2022-01-03","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":3},
{"id":469,"nom":"Oral","dateDeRendu":"2021-08-30","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":6},
{"id":470,"nom":"Projet","dateDeRendu":"2021-05-20","rendu":true,"note":0,"remarque":"Revoir le chapitre en entier","matiere":2,"etudiant":6},
{"id":471,"nom":"Contrôle","dateDeRendu":"2021-02-19","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":1},
{"id":472,"nom":"Projet","dateDeRendu":"2022-01-14","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":5},
{"id":473,"nom":"TD noté","dateDeRendu":"2021-12-01","rendu":false,"note":null,"remarque":"","matiere":2,"etudiant":3},
{"id":474,"nom":"TD noté","dateDeRendu":"2021-12-15","rendu":true,"note":18,"remarque":"Très bon devoir, bravo","matiere":4,"etudiant":5},
{"id":475,"nom":"Projet","dateDeRendu":"2021-08-22","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":4},
{"id":476,"nom":"Oral","dateDeRendu":"2021-10-31","rendu":true,"note":8,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":2,"etudiant":3},
{"id":477,"nom":"TD noté","dateDeRendu":"2021-12-21","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":7},
{"id":478,"nom":"Contrôle","dateDeRendu":"2021-07-12","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":2},
{"id":479,"nom":"Contrôle","dateDeRendu":"2021-02-10","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":6},
{"id":480,"nom":"TD noté","dateDeRendu":"2021-07-11","rendu":true,"note":0,"remarque":"Revoir le chapitre en entier","matiere":3,"etudiant":7},
{"id":481,"nom":"TD noté","dateDeRendu":"2021-09-23","rendu":true,"note":4,"remarque":"Revoir le chapitre en entier","matiere":3,"etudiant":3},
{"id":482,"nom":"Devoir maison","dateDeRendu":"2021-09-06","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":4},
{"id":483,"nom":"TD noté","dateDeRendu":"2021-05-05","rendu":true,"note":9,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":4,"etudiant":3},
{"id":484,"nom":"Projet","dateDeRendu":"2021-10-16","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":6},
{"id":485,"nom":"Oral","dateDeRendu":"2022-01-08","rendu":true,"note":14,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":2,"etudiant":2},
{"id":486,"nom":"TD noté","dateDeRendu":"2021-03-04","rendu":true,"note":13,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":3,"etudiant":3},
{"id":487,"nom":"Projet","dateDeRendu":"2021-06-21","rendu":true,"note":16,"remarque":"Très bon devoir, bravo","matiere":1,"etudiant":7},
{"id":488,"nom":"Devoir maison","dateDeRendu":"2021-04-27","rendu":false,"note":null,"remarque":"","matiere":1,"etudiant":3},
{"id":489,"nom":"Projet","dateDeRendu":"2021-10-30","rendu":true,"note":4,"remarque":"Revoir le chapitre en entier","matiere":2,"etudiant":1},
{"id":490,"nom":"Oral","dateDeRendu":"2021-04-03","rendu":true,"note":1,"remarque":"Revoir le chapitre en entier","matiere":2,"etudiant":6},
{"id":491,"nom":"Projet","dateDeRendu":"2021-07-25","rendu":false,"note":null,"remarque":"","matiere":3,"etudiant":4},
{"id":492,"nom":"Devoir maison","dateDeRendu":"2021-05-20","rendu":true,"note":10,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":2,"etudiant":2},
{"id":493,"nom":"Projet","dateDeRendu":"2021-10-15","rendu":true,"note":3,"remarque":"Revoir le chapitre en entier","matiere":3,"etudiant":2},
{"id":494,"nom":"Projet","dateDeRendu":"2021-04-03","rendu":true,"note":9,"remarque":"Des points ont été compris mais l'ensemble est à revoir","matiere":3,"etudiant":4},
{"id":495,"nom":"Projet","dateDeRendu":"2021-01-29","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":7},
{"id":496,"nom":"Devoir maison","dateDeRendu":"2021-09-14","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":6},
{"id":497,"nom":"TD noté","dateDeRendu":"2022-01-16","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":7},
{"id":498,"nom":"Contrôle","dateDeRendu":"2021-03-08","rendu":true,"note":11,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":1,"etudiant":2},
{"id":499,"nom":"Projet","dateDeRendu":"2021-12-03","rendu":true,"note":11,"remarque":"La majorité des points ont été compris, certains sont à paufiner","matiere":4,"etudiant":4},
{"id":500,"nom":"Devoir maison","dateDeRendu":"2021-08-31","rendu":false,"note":null,"remarque":"","matiere":4,"etudiant":7}];

export { bdInitialAssignments };
